name: PHP MVC API Install PHP and MySQL

on:
  push:
    branches:
      - main

jobs:
  install-php:
    - name: Update the package list
      run: sudo apt update && sudo apt -y upgrade

    - name: Install PHP
      run: sudo apt install -y php php-mysql

  setup-mysql:
    steps:
      - name: Configure database
        run: echo "mysql-server mysql-server/root_password password test-password" | sudo debconf-set-selections && \
          echo "mysql-server mysql-server/root_password_again password test-password" | sudo debconf-set-selections

      - name: Install MySQL
        run: sudo apt install -y mysql-server
      
      - name: Start MySQL server
        run: sudo service mysql start

      - name: Test connection to MySQL
        run: sudo mysql -h localhost -u root --password=test-password -e "SHOW DATABASES;"

  setup-nodejs:
    - name: Install NodeJS
      run: cd ~ && curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh && sudo bash /tmp/nodesource_setup.sh && sudo apt install -y nodejs

    - name: Install pm2
      run: sudo npm install pm2@latest -g

  deploy:
    - name: Start php server
      run: pm2 delete "php-app" || true && pm2 start "php -S localhost:8000" --name "php-app"

    - name: Save pm2 config
      run: pm2 save
