name: PHP MVC API Install PHP and MySQL

on:
  push:
    branches:
      - main

jobs:
  install-php-mysql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update the package list
        run: sudo apt update

      - name: Install PHP
        run: sudo apt install -y php php-mysql

      - name: Install MySQL
        run: sudo apt install -y mysql-server

      - name: Secure MySQL installation
        run: sudo mysql_secure_installation

      - name: Test PHP connection to MySQL
        run: |
          <?php
            $conn = new mysqli('localhost', 'root', '', 'mysql');

            if (!$conn) {
                die('Connection failed: ' . mysqli_connect_error());
            }

            echo 'Connected to MySQL successfully.';

            mysqli_close($conn);
          ?>
